# Project 2: Housing Price Prediction – Pass 16

## Problem Definition

State the business problem. Translate the business problem into a Data Science problem by stating what kind of problem it is ( supervised vs unsupervised ) and whether it is a classification, regression, or clustering problem.

Statement:

We want to predict housing sale prices based on various correlated feature data. This is a *supervised regression* problem, where the target of the prediction is sales prices. To accomplish this, we use a regression model alongside Regression prediction techniques, as well as feature scaling and regularization to minimize the RMS percentage error.

## Data Collection/Sources

Data Collection describes the process by which we obtain the data for use in the project. In this case, our data comes from S3 storage buckets on AWS, which we load into memory (variables) via URLs by passing them to the read_csv function of the pandas python library (more on that soon).

The data comes in one large set containing the full data available for use in the project. It is supplemented by a data dictionary that describes the set, the data types of the included data, and other information relevant to its use.

Finally, to store the data in a form we can work with in memory, we use a storage structure called a DataFrame object from the pandas python library. This object allows us to quickly view the data and preview operations on the data without changing it, as well as make updates to the data in a highly intuitive way.

Load Pandas, Numpy, and Matplotlib modules

In [1]:
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm

from sklearn import datasets, metrics
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import LabelEncoder

Load data Train.csv from AWS S3:

In [2]:
# url
url = 'https://ddc-datascience.s3.amazonaws.com/Projects/Project.2-Housing/Data/Housing.Data.csv'

Next, make a preview DataFrame to look at columns:

In [3]:
# make preview
df_preview = pd.read_csv(url)
df_preview

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,905101070,20,RL,62.0,14299,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,7,2007,WD,Normal,115400
1,905101330,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,Shed,500,10,2006,WD,Normal,90000
2,903454090,50,RM,50.0,9000,Pave,NaN,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,141000
3,533244030,60,FV,68.0,7379,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,254000
4,909252020,70,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,4,2009,WD,Normal,155000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2632,903231070,50,RM,52.0,6240,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,400,9,2006,WD,Normal,114500
2633,906201021,80,RL,74.0,10778,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,162000
2634,533253070,120,RL,61.0,3782,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,211500
2635,527376100,20,RL,78.0,10140,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,8,2009,WD,Normal,165000
2636,528292060,60,RL,41.0,12460,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,225000

In [4]:
# preview all column names
df_preview.columns

Index(['PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area', 'Street',
       'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config',
       'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type',
       'House Style', 'Overall Qual', 'Overall Cond', 'Year Built',
       'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st',
       'Exterior 2nd', 'Mas Vnr Type', 'Mas Vnr Area', 'Exter Qual',
       'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2',
       'Bsmt Unf SF', 'Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air',
       'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual',
       'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Fireplace Qu',
       'Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Cars',
       'Garage Area', 'Garage Qual', 'Garage Cond', 'Paved Drive',
       'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
       'Screen Porch', 'Pool Area', 'Pool QC', 'Fence', 'Misc Feature',
       'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type', 'Sale Condition',
       'SalePrice'],
      dtype='object')

Define the target column (and features types, if required):

In [5]:
# define target column (by name) and features column(s)
target_col = "SalePrice"
feature_types = ['float64', 'int64', 'O']

Create list of target col and feature cols:

In [6]:
# use list comprehension to generate list of target col + selected feature cols
selected_cols = [
    col
    for col in df_preview.columns
    if (col == target_col) or (df_preview[col].dtype in feature_types)
]
selected_cols

['PID',
 'MS SubClass',
 'MS Zoning',
 'Lot Frontage',
 'Lot Area',
 'Street',
 'Alley',
 'Lot Shape',
 'Land Contour',
 'Utilities',
 'Lot Config',
 'Land Slope',
 'Neighborhood',
 'Condition 1',
 'Condition 2',
 'Bldg Type',
 'House Style',
 'Overall Qual',
 'Overall Cond',
 'Year Built',
 'Year Remod/Add',
 'Roof Style',
 'Roof Matl',
 'Exterior 1st',
 'Exterior 2nd',
 'Mas Vnr Type',
 'Mas Vnr Area',
 'Exter Qual',
 'Exter Cond',
 'Foundation',
 'Bsmt Qual',
 'Bsmt Cond',
 'Bsmt Exposure',
 'BsmtFin Type 1',
 'BsmtFin SF 1',
 'BsmtFin Type 2',
 'BsmtFin SF 2',
 'Bsmt Unf SF',
 'Total Bsmt SF',
 'Heating',
 'Heating QC',
 'Central Air',
 'Electrical',
 '1st Flr SF',
 '2nd Flr SF',
 'Low Qual Fin SF',
 'Gr Liv Area',
 'Bsmt Full Bath',
 'Bsmt Half Bath',
 'Full Bath',
 'Half Bath',
 'Bedroom AbvGr',
 'Kitchen AbvGr',
 'Kitchen Qual',
 'TotRms AbvGrd',
 'Functional',
 'Fireplaces',
 'Fireplace Qu',
 'Garage Type',
 'Garage Yr Blt',
 'Garage Finish',
 'Garage Cars',
 'Garage Area',
 'Garage Qual',
 'Garage Cond',
 'Paved Drive',
 'Wood Deck SF',
 'Open Porch SF',
 'Enclosed Porch',
 '3Ssn Porch',
 'Screen Porch',
 'Pool Area',
 'Pool QC',
 'Fence',
 'Misc Feature',
 'Misc Val',
 'Mo Sold',
 'Yr Sold',
 'Sale Type',
 'Sale Condition',
 'SalePrice']

Read in the data from .csv using target_col and feature_types:

In [7]:
df_preview[selected_cols].dtypes.unique()

array([dtype('int64'), dtype('O'), dtype('float64')], dtype=object)

In [8]:
# make dataframe
df = pd.read_csv( url, usecols=selected_cols )

Finally, check the dataframe:

In [9]:
# check dataframe
df

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,905101070,20,RL,62.0,14299,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,7,2007,WD,Normal,115400
1,905101330,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,Shed,500,10,2006,WD,Normal,90000
2,903454090,50,RM,50.0,9000,Pave,NaN,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,141000
3,533244030,60,FV,68.0,7379,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,254000
4,909252020,70,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,4,2009,WD,Normal,155000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2632,903231070,50,RM,52.0,6240,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,400,9,2006,WD,Normal,114500
2633,906201021,80,RL,74.0,10778,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,162000
2634,533253070,120,RL,61.0,3782,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,211500
2635,527376100,20,RL,78.0,10140,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,8,2009,WD,Normal,165000
2636,528292060,60,RL,41.0,12460,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,225000

## Data Cleaning

Data Cleaning is the process of preparing the data set for use in analysis. Many data sets contain bad or null (empty) values, which can cause errors when trying to work with the data and use it in code. Cleaning the data involves removing bad (null-containing) columns and/or rows from the set, as well as imputing (replacing via insertion) similar data into fields with missing or unusable values.

Here, to clean the data, we mostly use the pandas drop function included with pandas DataFrame objects, which allow us to drop columns and rows according to conditions we specify, much like SQL WHERE clauses.

#### Examine the data using tools we have used in class. You should be identifying the various columns such as ...

    - target column
    - feature columns
    - identifier columns
    - null columns
    - null rows

    Tools you should be using include, but are not limited to:

    - head
    - tail
    - shape
    - size
    - info
    - describe
    - nunique
    - unique
    - isnull/isna

First, define the target column:

In [10]:
# check target_col
target_col

'SalePrice'

- head

In [11]:
# head
df.head()

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,905101070,20,RL,62.0,14299,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,7,2007,WD,Normal,115400
1,905101330,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,Shed,500,10,2006,WD,Normal,90000
2,903454090,50,RM,50.0,9000,Pave,NaN,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,141000
3,533244030,60,FV,68.0,7379,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,254000
4,909252020,70,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,4,2009,WD,Normal,155000

- tail

In [12]:
# tail
df.tail()

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
2632,903231070,50,RM,52.0,6240,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,400,9,2006,WD,Normal,114500
2633,906201021,80,RL,74.0,10778,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,162000
2634,533253070,120,RL,61.0,3782,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,211500
2635,527376100,20,RL,78.0,10140,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,8,2009,WD,Normal,165000
2636,528292060,60,RL,41.0,12460,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,225000

- shape

In [13]:
# shape
df.shape

(2637, 81)

- size

In [14]:
# size
df.size

213597

- info

In [15]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2637 entries, 0 to 2636
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PID              2637 non-null   int64
 1   MS SubClass      2637 non-null   int64
 2   MS Zoning        2637 non-null   object
 3   Lot Frontage     2188 non-null   float64
 4   Lot Area         2637 non-null   int64
 5   Street           2637 non-null   object
 6   Alley            180 non-null    object
 7   Lot Shape        2637 non-null   object
 8   Land Contour     2637 non-null   object
 9   Utilities        2637 non-null   object
 10  Lot Config       2637 non-null   object
 11  Land Slope       2637 non-null   object
 12  Neighborhood     2637 non-null   object
 13  Condition 1      2637 non-null   object
 14  Condition 2      2637 non-null   object
 15  Bldg Type        2637 non-null   object
 16  House Style      2637 non-null   object
 17  Overall Qual     2637 non-null   int64
 18  Overall Cond     2637 non-null   int64
 19  Year Built       2637 non-null   int64
 20  Year Remod/Add   2637 non-null   int64
 21  Roof Style       2637 non-null   object
 22  Roof Matl        2637 non-null   object
 23  Exterior 1st     2637 non-null   object
 24  Exterior 2nd     2637 non-null   object
 25  Mas Vnr Type     1030 non-null   object
 26  Mas Vnr Area     2614 non-null   float64
 27  Exter Qual       2637 non-null   object
 28  Exter Cond       2637 non-null   object
 29  Foundation       2637 non-null   object
 30  Bsmt Qual        2564 non-null   object
 31  Bsmt Cond        2564 non-null   object
 32  Bsmt Exposure    2561 non-null   object
 33  BsmtFin Type 1   2564 non-null   object
 34  BsmtFin SF 1     2636 non-null   float64
 35  BsmtFin Type 2   2563 non-null   object
 36  BsmtFin SF 2     2636 non-null   float64
 37  Bsmt Unf SF      2636 non-null   float64
 38  Total Bsmt SF    2636 non-null   float64
 39  Heating          2637 non-null   object
 40  Heating QC       2637 non-null   object
 41  Central Air      2637 non-null   object
 42  Electrical       2637 non-null   object
 43  1st Flr SF       2637 non-null   int64
 44  2nd Flr SF       2637 non-null   int64
 45  Low Qual Fin SF  2637 non-null   int64
 46  Gr Liv Area      2637 non-null   int64
 47  Bsmt Full Bath   2635 non-null   float64
 48  Bsmt Half Bath   2635 non-null   float64
 49  Full Bath        2637 non-null   int64
 50  Half Bath        2637 non-null   int64
 51  Bedroom AbvGr    2637 non-null   int64
 52  Kitchen AbvGr    2637 non-null   int64
 53  Kitchen Qual     2637 non-null   object
 54  TotRms AbvGrd    2637 non-null   int64
 55  Functional       2637 non-null   object
 56  Fireplaces       2637 non-null   int64
 57  Fireplace Qu     1353 non-null   object
 58  Garage Type      2492 non-null   object
 59  Garage Yr Blt    2490 non-null   float64
 60  Garage Finish    2490 non-null   object
 61  Garage Cars      2636 non-null   float64
 62  Garage Area      2636 non-null   float64
 63  Garage Qual      2490 non-null   object
 64  Garage Cond      2490 non-null   object
 65  Paved Drive      2637 non-null   object
 66  Wood Deck SF     2637 non-null   int64
 67  Open Porch SF    2637 non-null   int64
 68  Enclosed Porch   2637 non-null   int64
 69  3Ssn Porch       2637 non-null   int64
 70  Screen Porch     2637 non-null   int64
 71  Pool Area        2637 non-null   int64
 72  Pool QC          11 non-null     object
 73  Fence            528 non-null    object
 74  Misc Feature     96 non-null     object
 75  Misc Val         2637 non-null   int64
 76  Mo Sold          2637 non-null   int64
 77  Yr Sold          2637 non-null   int64
 78  Sale Type        2637 non-null   object
 79  Sale Condition   2637 non-null   object
 80  SalePrice        2637 non-null   int64
dtypes: float64(11), int64(27), object(43)
memory usage: 1.6+ MB

- describe

In [16]:
# describe
df.describe()

,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2.637000e+03,2637.000000,2188.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2614.000000,2636.000000,...,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000
mean,7.141301e+08,57.349261,69.166819,10044.694729,6.097459,5.569966,1971.288586,1984.202882,101.887911,438.441199,...,94.305271,46.984452,22.813424,2.368601,15.775123,2.130072,42.014031,6.243838,2007.795601,179986.230186
std,1.887527e+08,42.499091,23.356779,6742.549521,1.411522,1.118262,30.306986,20.913077,179.578232,449.602326,...,126.927272,66.564333,61.177638,23.160600,55.783751,35.140140,393.158781,2.722093,1.306403,78309.251522
min,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,5.284770e+08,20.000000,58.000000,7436.000000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,5.354530e+08,50.000000,68.000000,9450.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,368.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,9.071870e+08,70.000000,80.000000,11526.000000,7.000000,6.000000,2001.000000,2004.000000,164.000000,732.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213000.000000
max,1.007100e+09,190.000000,313.000000,164660.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1424.000000,742.000000,584.000000,407.000000,576.000000,800.000000,12500.000000,12.000000,2010.000000,745000.000000

- nunique

In [17]:
# nunique
df.nunique().sort_values( ascending = False )

PID               2637
Lot Area          1799
Gr Liv Area       1216
Bsmt Unf SF       1080
1st Flr SF        1022
                  ...
Bsmt Half Bath       3
Paved Drive          3
Street               2
Alley                2
Central Air          2
Length: 81, dtype: int64

In [18]:
# normalize to look for ID column(s)
df.nunique().sort_values( ascending = False ) / df.shape[0] * 100

PID               100.000000
Lot Area           68.221464
Gr Liv Area        46.113007
Bsmt Unf SF        40.955631
1st Flr SF         38.756162
                     ...
Bsmt Half Bath      0.113766
Paved Drive         0.113766
Street              0.075844
Alley               0.075844
Central Air         0.075844
Length: 81, dtype: float64

- unique

In [19]:
# unique
df[target_col].unique()

array([115400,  90000, 141000, 254000, 155000, 125000, 194500, 185000,
       235000, 152000, 201000, 207000, 192000, 174000, 190000, 176000,
       384500, 395039, 167000, 165000, 195000, 104500, 161000, 245700,
       226001, 153500, 139000,  35000, 181000, 212000, 156000, 139500,
       225000,  12789, 157500, 110000, 130000, 263000, 205000, 117000,
       200624, 120000, 137900, 245500, 107000, 327000,  93000, 145250,
       168000, 169900, 122000, 161750, 188000, 149500, 421250, 305000,
        50138, 136000, 150750, 307000, 241000,  86900, 202500,  93500,
       121000, 107500, 336000, 213000, 129000, 170000, 337500, 535000,
       173500, 162000,  37900, 158500,  94000, 350000, 140000, 409900,
       115000, 177000,  94750, 121600, 128500, 301000, 230000, 151000,
       137500,  85500, 129400, 191500, 250000, 135000, 119000, 150000,
       178000, 163900, 199000, 203000, 178900, 180000, 182000, 177900,
       122500, 134900, 132000, 147983,  68500, 158000, 260261,  64500,
       140500, 222000, 301500, 138500, 113000, 135750, 213500, 197900,
       134432, 270000, 237000, 196000, 167840, 151400, 138000, 118000,
       159434, 160000,  99500, 311872, 240000, 144000, 145400, 584500,
       230500, 315000, 216837, 183000, 143000, 229456,  85000, 108500,
        89500, 109500, 127000, 235128,  76500, 254900, 188900, 149900,
       154000, 251000,  88000, 143500, 157000, 269790, 105000, 120500,
       104900, 171000,  58500, 234000, 272500, 215000, 129250, 106900,
       214000, 175000, 262500, 300000, 112000, 193879, 137000, 139950,
       142000, 187500, 188500, 209500, 126000, 119500, 120750, 111000,
       135500, 126500, 201800, 128250, 114500, 290000, 167800, 124000,
       102000, 197000, 236000, 249000, 152400, 194000, 379000, 184900,
       103000, 139400, 172500,  75190, 445000, 125500, 128000, 159900,
       333168, 172000, 280000, 184000,  97000, 154400, 259500, 154500,
       116000, 167900, 470000,  62383,  99900, 190550, 108000, 356000,
       186000, 239000, 119164,  97500, 212700, 129900, 287500, 172400,
       260000, 131000, 102776, 216500, 186700, 169000, 106000, 233170,
       212500, 293000, 325300, 394432, 152500, 610000, 294000, 150909,
       209700, 403000, 207500, 215700, 303477, 412083, 356383,  57625,
       147500, 145000, 321000, 146000, 235500, 293200, 438780, 148000,
       185500, 141500, 156500, 192100,  87000,  13100, 200000, 104000,
       132500, 166000, 255500, 159895, 198500, 183900, 263435,  68400,
        98000, 112500, 386250, 210000, 111900, 140750, 128950, 243500,
       238500, 200141, 124500, 171900, 277000,  82000, 239900,  83000,
       210900, 136900, 229800, 217500, 258000, 228500, 218000, 221300,
       164500, 111250, 181755, 103500, 194700, 163000, 342000, 173000,
       133000, 187000, 203135, 257500, 335000, 100500, 191000,  87500,
       147000, 214900, 213250, 160500, 134000, 213490, 168500, 220000,
        93900, 501837, 136500, 161900, 301600, 179665, 151500, 217300,
        82500, 255000, 372000, 114900,  80000, 278000, 189000, 159000,
       222500, 147900, 462000, 285000, 404000, 133500, 264966, 223000,
       117250, 119916, 319900,  95000,  96000, 274000, 492000, 219000,
       153000, 119900, 309000, 153337, 164000, 107400, 217000, 255900,
       211000, 165250, 130500, 227000, 383970, 118500, 148800, 129500,
       105900, 227875, 123000, 113500, 177625, 320000,  79400, 149300,
       119200,  60000, 149000, 310013, 180500,  68104, 117500,  78500,
       193500, 148400, 186800, 131500,  34900, 341000, 126175, 189950,
        79900, 372402, 275000, 181900, 175500, 315500, 219500, 153575,
       325624, 186500, 197600, 137250, 269500, 218836, 206580, 138800,
       261500, 377426, 241600, 224500, 124400, 475000, 235876, 265000,
       145500, 143750, 185101,  67000, 183600,  95541, 116500, 136870,
       163990, 111500, 109900, 123500, 256300, 237500, 179400, 253293,
       485000, 134800, 370967, 138400,  84900, 125200, 228950, 118858,
       129200, 139900, 226700, 196500, 114504, 283463,  91900, 193000,
       161500,  81000,  93850, 163500, 259000, 100000, 172900,  79000,
       176500, 228000,  80900, 375000, 159500, 122600, 198600, 164900,
       337000, 130250, 166500, 248500, 232000, 125900, 246500, 111750,
       162500, 133700, 362500, 253000, 265979, 299800, 178400, 322400,
       336860, 355000, 226000,  75000, 256000, 340000,  92000, 325000,
       295000, 281500, 133900, 167500, 279700, 138887, 145100, 256900,
       179900, 310090, 144750, 204500, 306000, 437154, 324000, 345000,
       213750, 295493, 192140, 189500, 185485,  96900, 302000,  67500,
       181500, 252678,  55000,  72000, 370000, 204000,  81400, 216000,
       145900, 120875, 360000, 287000, 241500, 200500, 221500, 284700,
       312500, 179540, 392000, 378500, 318000, 174850, 146800, 322500,
       254750, 128600, 116900,  91000, 149350, 177500, 204750, 361919,
       175900, 123600,  61500, 129850,  63000, 143900, 169990, 287602,
       158450, 198000, 310000, 221370, 199900, 276000, 281213, 189900,
       323262, 231000, 156932, 171500, 330000, 239500, 171925, 150500,
       179000,  86000, 187750, 169500, 292500, 198444, 162900, 140200,
        99000, 147400,  84000, 119750, 136300, 191750, 127500, 382500,
       110500,  61000, 134500,  80500, 410000, 197500, 291000, 167240,
       248900, 142600, 290941, 199500, 165400,  81300, 128200, 271000,
       398800, 124900, 221000,  98300, 165500, 326000, 257000, 224900,
       319500, 179500, 249700, 229000, 165150, 128900, 146500, 188700,
       117600, 131400, 359900, 245000, 297000, 103600, 136905, 252000,
       500000,  73000, 318061, 208000, 282500, 500067, 209000, 556581,
       142500, 268000, 169985, 239799, 377500, 244600, 183500, 266500,
       142953,  94900, 206300, 390000, 144500, 311500, 146900, 200825,
       450000, 144152,  99600, 114000, 204900, 298236, 318750, 260400,
       316600, 267000, 119600, 195500, 465000, 165600, 108480, 176400,
       374000, 359100,  64000, 185900, 394617, 101800, 334000, 212999,
       185850, 274725, 144900, 184500, 263550, 316500, 286000, 149700,
       147110, 105500, 328000, 187100, 281000, 153600, 155900, 282922,
       294464, 231500, 102900, 349265,  40000, 153900, 176432,  81500,
       168165, 208900, 122900, 244000, 279500, 242500, 124100, 192350,
       103200, 112900,  79500, 376162, 257076,  39300, 402000, 354000,
        96500,  89000, 279900, 244400, 142100, 160250, 277500, 415000,
       395000, 148500, 177439, 154300, 385000, 271900, 208500, 223500,
       298751,  72500,  84500,  35311, 218689,  45000, 109008, 179200,
       150900, 121500,  50000, 279000, 193800,  75500, 275500, 545224,
       123900, 239686, 457347, 248000, 418000,  76000, 212300, 177594,
       246578, 135960,  90350, 236500, 113722, 238000, 176485, 242000,
       156450,  99800, 378000, 219210, 137450, 168675, 555000, 206000,
       206900, 231713, 194201, 395192, 260116, 113700, 266000, 243000,
       280750, 170440, 132250, 131250,  66500, 200100, 154900, 226750,
       166800, 103400,  62500,  91500,  94500, 426000, 155891, 308030,
       129800,  80400, 214500, 248328, 179600,  52500, 372500, 246990,
       615000, 264132, 164990, 383000, 345474, 392500,  51689,  79275,
       263400, 209200,  93369, 230348, 135900,  91300, 466500, 108538,
       336820, 338500, 192500, 131900, 184750, 381000, 441929,  85400,
       144800, 319000, 339750, 180400, 224243, 201490,  59000, 178740,
       268500, 284000, 297900, 262000, 155835, 107900, 479069, 187687,
        52000, 154204, 245350, 367294, 179781, 190500,  87550, 468000,
        78000, 329900, 185088, 372397, 183200, 267300, 232500, 305900,
       417500, 202900, 370878,  83500, 213133, 328900, 412500, 233000,
       317500, 142250, 118900, 202665, 611657, 227680,  68000, 405749,
       106250, 338931, 387000, 315750, 446261, 203160, 267916, 332000,
       455000, 178750,  71000,  65000, 232698, 247000,  70000, 224000,
       106500, 143250, 265900, 313000, 131750, 240050, 401179, 184100,
       240900, 226500, 157900, 289000, 219990, 109000, 156820, 143450,
       287090, 274300, 286500, 139600, 118964, 405000, 172785, 233230,
       146300, 316000,  98600, 402861, 538000, 250580, 233500,  88750,
       195800, 274970, 173900, 173733, 233555,  97900, 198900, 208300,
       284500, 142125, 167300, 142900, 148325, 272000, 215200, 373000,
       262280, 115500, 332200, 419005, 210400,  82375, 160200, 247900,
       745000, 234250,  98500, 174500, 282000,  55993, 314813, 625000,
       182900,  44000, 212109, 232600, 118400, 415298, 174190, 158900,
        94550, 143195, 171750, 264500, 221800, 205950, 344133, 246000,
       451950, 195400, 159950, 369900,  89900, 174900, 211500])

- isnull

In [20]:
# isnull
df.isnull().sum().sort_values( ascending = False )

Pool QC           2626
Misc Feature      2541
Alley             2457
Fence             2109
Mas Vnr Type      1607
                  ...
Mo Sold              0
Yr Sold              0
Sale Type            0
Sale Condition       0
SalePrice            0
Length: 81, dtype: int64

In [21]:
# percent null by column
(df.isnull().sum() / df.shape[0]).sort_values( ascending = False ) * 100

Pool QC           99.582859
Misc Feature      96.359499
Alley             93.174061
Fence             79.977247
Mas Vnr Type      60.940463
                    ...
Mo Sold            0.000000
Yr Sold            0.000000
Sale Type          0.000000
Sale Condition     0.000000
SalePrice          0.000000
Length: 81, dtype: float64

In [22]:
# look at unique values in the col-by-col null counts to classify cols
((df.isnull().sum() / df.shape[0]).sort_values( ascending = False ) * 100).unique()

array([9.95828593e+01, 9.63594994e+01, 9.31740614e+01, 7.99772469e+01,
       6.09404626e+01, 4.86916951e+01, 1.70269245e+01, 5.57451650e+00,
       5.49867273e+00, 2.88206295e+00, 2.80621919e+00, 2.76829731e+00,
       8.72203261e-01, 7.58437619e-02, 3.79218809e-02, 0.00000000e+00])

In [23]:
# check to see if anything is not zero -- should return 0 if no nulls
df.isnull().sum().sum()

np.int64(14208)

In [24]:
# how many rows with at least one null
num_rows_with_nulls = df.isna().any(axis=1).sum()
int(num_rows_with_nulls)

2637

The target (SalePrice) contains no nulls, but the feature (Lot Frontage) contains about 17% null values. To address this, we can impute values using the median value in that column.

- dtypes

In [25]:
# dtypes
df.dtypes

PID                 int64
MS SubClass         int64
MS Zoning          object
Lot Frontage      float64
Lot Area            int64
                   ...
Mo Sold             int64
Yr Sold             int64
Sale Type          object
Sale Condition     object
SalePrice           int64
Length: 81, dtype: object

Examine null columns, columns with some nulls, and columns with no nulls:

In [26]:
# display columns with all null values
df.isnull().sum()[df.isnull().sum() == df.shape[0]]

Series([], dtype: int64)

In [27]:
# count these
int(df.isnull().sum()[df.isnull().sum() == df.shape[0]].count())

0

In [28]:
# show columns with some null values
df.isnull().sum()[(df.isnull().sum() != df.shape[0]) & (df.isnull().sum() != 0)].sort_values( ascending = False )

Pool QC           2626
Misc Feature      2541
Alley             2457
Fence             2109
Mas Vnr Type      1607
Fireplace Qu      1284
Lot Frontage       449
Garage Cond        147
Garage Yr Blt      147
Garage Finish      147
Garage Qual        147
Garage Type        145
Bsmt Exposure       76
BsmtFin Type 2      74
Bsmt Qual           73
BsmtFin Type 1      73
Bsmt Cond           73
Mas Vnr Area        23
Bsmt Half Bath       2
Bsmt Full Bath       2
BsmtFin SF 1         1
Total Bsmt SF        1
Bsmt Unf SF          1
BsmtFin SF 2         1
Garage Area          1
Garage Cars          1
dtype: int64

In [29]:
# count these
int(df.isnull().sum()[(df.isnull().sum() != df.shape[0]) & (df.isnull().sum() != 0)].count())

26

In [30]:
# columns with no nulls
df.isnull().sum()[df.isnull().sum() == 0]

PID                0
MS SubClass        0
MS Zoning          0
Lot Area           0
Street             0
Lot Shape          0
Land Contour       0
Utilities          0
Lot Config         0
Land Slope         0
Neighborhood       0
Condition 1        0
Condition 2        0
Bldg Type          0
House Style        0
Overall Qual       0
Overall Cond       0
Year Built         0
Year Remod/Add     0
Roof Style         0
Roof Matl          0
Exterior 1st       0
Exterior 2nd       0
Exter Qual         0
Exter Cond         0
Foundation         0
Heating            0
Heating QC         0
Central Air        0
Electrical         0
1st Flr SF         0
2nd Flr SF         0
Low Qual Fin SF    0
Gr Liv Area        0
Full Bath          0
Half Bath          0
Bedroom AbvGr      0
Kitchen AbvGr      0
Kitchen Qual       0
TotRms AbvGrd      0
Functional         0
Fireplaces         0
Paved Drive        0
Wood Deck SF       0
Open Porch SF      0
Enclosed Porch     0
3Ssn Porch         0
Screen Porch       0
Pool Area          0
Misc Val           0
Mo Sold            0
Yr Sold            0
Sale Type          0
Sale Condition     0
SalePrice          0
dtype: int64

In [31]:
# count these
int(df.isnull().sum()[df.isnull().sum() == 0].count())

55

#### Target: Value Counts

In [32]:
# value counts on target
df[target_col].value_counts( dropna = False )

SalePrice
140000    31
135000    30
130000    28
155000    24
160000    22
          ..
160200     1
174190     1
415298     1
118400     1
232600     1
Name: count, Length: 983, dtype: int64

In [33]:
# value counts normalized
df[target_col].value_counts( dropna = False, normalize = True ) * 100

SalePrice
140000    1.175578
135000    1.137656
130000    1.061813
155000    0.910125
160000    0.834281
            ...
160200    0.037922
174190    0.037922
415298    0.037922
118400    0.037922
232600    0.037922
Name: proportion, Length: 983, dtype: float64

In [34]:
# target col size/shape
df[[target_col]].shape[0]

2637

In [35]:
# sum of nulls in target
int(df[[target_col]].isnull().sum().iloc[0])

0

In [36]:
# sum of non-nulls in target
df[[target_col]].shape[0] - int(df[[target_col]].isnull().sum().iloc[0])

2637

There are no nulls in the target column, which means no rows will need to be dropped on its account.

In [37]:
df.shape, df.size

((2637, 81), 213597)

In [38]:
df.drop(columns = [target_col]).columns

Index(['PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area', 'Street',
       'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config',
       'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type',
       'House Style', 'Overall Qual', 'Overall Cond', 'Year Built',
       'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st',
       'Exterior 2nd', 'Mas Vnr Type', 'Mas Vnr Area', 'Exter Qual',
       'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2',
       'Bsmt Unf SF', 'Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air',
       'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual',
       'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Fireplace Qu',
       'Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Cars',
       'Garage Area', 'Garage Qual', 'Garage Cond', 'Paved Drive',
       'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
       'Screen Porch', 'Pool Area', 'Pool QC', 'Fence', 'Misc Feature',
       'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type', 'Sale Condition'],
      dtype='object')

In [39]:
df.isna().any(axis=1).sum()

np.int64(2637)

In [40]:
df.columns

Index(['PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area', 'Street',
       'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config',
       'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type',
       'House Style', 'Overall Qual', 'Overall Cond', 'Year Built',
       'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st',
       'Exterior 2nd', 'Mas Vnr Type', 'Mas Vnr Area', 'Exter Qual',
       'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2',
       'Bsmt Unf SF', 'Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air',
       'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual',
       'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Fireplace Qu',
       'Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Cars',
       'Garage Area', 'Garage Qual', 'Garage Cond', 'Paved Drive',
       'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
       'Screen Porch', 'Pool Area', 'Pool QC', 'Fence', 'Misc Feature',
       'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type', 'Sale Condition',
       'SalePrice'],
      dtype='object')

#### Summary:

This abridged dataset contains 2637 rows and 81 columns, making for a total of 5274 entries of data. Many of these fields are null.

Details:

  - target column: 'SalePrice'
  - feature columns: [
  'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area', 'Street',
       'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config',
       'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type',
       'House Style', 'Overall Qual', 'Overall Cond', 'Year Built',
       'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st',
       'Exterior 2nd', 'Mas Vnr Type', 'Mas Vnr Area', 'Exter Qual',
       'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2',
       'Bsmt Unf SF', 'Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air',
       'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual',
       'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Fireplace Qu',
       'Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Cars',
       'Garage Area', 'Garage Qual', 'Garage Cond', 'Paved Drive',
       'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
       'Screen Porch', 'Pool Area', 'Pool QC', 'Fence', 'Misc Feature',
       'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type', 'Sale Condition'
  ]
  - identifier columns: 'PID'
  - null columns: 0
  - null rows (target): 0
  - null rows (any): 2637 / 2637 (~100%)

Next, we split our data into three groups by data type in order to properly clean each group according to its particular needs.

In [41]:
# declare a df_all DataFrame for all the data
df_all = df.copy()

In [47]:
# Split df into three separate data frames --> df_float
df_float = df_all.drop( columns = [target_col] ).select_dtypes( include = ['float64'] )
df_float = pd.concat([pd.DataFrame(df[target_col]), df_float], axis = 1)
df_float.head()

,SalePrice,Lot Frontage,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Bsmt Full Bath,Bsmt Half Bath,Garage Yr Blt,Garage Cars,Garage Area
0,115400,62.0,0.0,513.0,144.0,348.0,1005.0,1.0,0.0,1964.0,2.0,440.0
1,90000,72.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1967.0,2.0,516.0
2,141000,50.0,0.0,0.0,0.0,780.0,780.0,0.0,0.0,1979.0,1.0,544.0
3,254000,68.0,0.0,484.0,0.0,491.0,975.0,1.0,0.0,2000.0,2.0,592.0
4,155000,60.0,0.0,350.0,210.0,0.0,560.0,1.0,0.0,1971.0,2.0,576.0

In [46]:
# Split df into three separate data frames --> df_int
df_int = df_all.drop( columns = [target_col] ).select_dtypes( include = ['int64'] )
df_int = pd.concat([pd.DataFrame(df[target_col]), df_int], axis = 1)
df_int.head()

,SalePrice,PID,MS SubClass,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,1st Flr SF,2nd Flr SF,...,Fireplaces,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold
0,115400,905101070,20,14299,4,3,1964,1964,1005,0,...,0,0,0,0,0,0,0,0,7,2007
1,90000,905101330,90,10791,4,5,1967,1967,1296,0,...,0,0,0,0,0,0,0,500,10,2006
2,141000,903454090,50,9000,6,6,1937,1950,780,595,...,1,0,162,0,0,126,0,0,12,2007
3,254000,533244030,60,7379,8,5,2000,2000,975,873,...,1,280,184,0,0,0,0,0,4,2010
4,155000,909252020,70,7200,7,9,1936,2007,575,560,...,0,256,0,0,0,0,0,0,4,2009

In [48]:
# Split df into three separate data frames --> df_object
df_object = df_all.drop( columns = [target_col] ).select_dtypes( include = ['O'] )
df_object = pd.concat([pd.DataFrame(df[target_col]), df_object], axis = 1)
df_object.head()

,SalePrice,MS Zoning,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,...,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Pool QC,Fence,Misc Feature,Sale Type,Sale Condition
0,115400,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,...,Detchd,Unf,TA,TA,N,NaN,MnPrv,NaN,WD,Normal
1,90000,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,...,CarPort,Unf,TA,TA,Y,NaN,NaN,Shed,WD,Normal
2,141000,RM,Pave,NaN,Reg,Bnk,AllPub,Inside,Gtl,IDOTRR,...,Detchd,Unf,TA,TA,P,NaN,NaN,NaN,WD,Normal
3,254000,FV,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Somerst,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
4,155000,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,SWISU,...,Detchd,RFn,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal

#### Data Cleaning — Floats

In [ ]:
# start by initializing df to df_object
df = df_object.copy()

- head

In [ ]:
# head
df.head()

,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,905101070,20,62.0,14299,4,3,1964,1964,0.0,513.0,...,0,0,0,0,0,0,0,7,2007,115400
1,905101330,90,72.0,10791,4,5,1967,1967,0.0,0.0,...,0,0,0,0,0,0,500,10,2006,90000
2,903454090,50,50.0,9000,6,6,1937,1950,0.0,0.0,...,0,162,0,0,126,0,0,12,2007,141000
3,533244030,60,68.0,7379,8,5,2000,2000,0.0,484.0,...,280,184,0,0,0,0,0,4,2010,254000
4,909252020,70,60.0,7200,7,9,1936,2007,0.0,350.0,...,256,0,0,0,0,0,0,4,2009,155000

- tail

In [ ]:
# tail
df.tail()

,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
2632,903231070,50,52.0,6240,6,6,1934,1950,0.0,0.0,...,112,0,0,0,0,0,400,9,2006,114500
2633,906201021,80,74.0,10778,7,6,1990,1991,0.0,460.0,...,114,36,0,0,0,0,0,7,2009,162000
2634,533253070,120,61.0,3782,8,5,1981,1981,0.0,960.0,...,133,78,0,0,0,0,0,9,2009,211500
2635,527376100,20,78.0,10140,6,5,1974,1974,174.0,0.0,...,0,0,0,0,0,0,0,8,2009,165000
2636,528292060,60,41.0,12460,7,5,1999,2000,0.0,870.0,...,144,44,0,0,0,0,0,5,2008,225000

- shape

In [ ]:
# shape
df.shape

(2637, 38)

- size

In [ ]:
# size
df.size

100206

- info

In [ ]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2637 entries, 0 to 2636
Data columns (total 38 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PID              2637 non-null   int64
 1   MS SubClass      2637 non-null   int64
 2   Lot Frontage     2188 non-null   float64
 3   Lot Area         2637 non-null   int64
 4   Overall Qual     2637 non-null   int64
 5   Overall Cond     2637 non-null   int64
 6   Year Built       2637 non-null   int64
 7   Year Remod/Add   2637 non-null   int64
 8   Mas Vnr Area     2614 non-null   float64
 9   BsmtFin SF 1     2636 non-null   float64
 10  BsmtFin SF 2     2636 non-null   float64
 11  Bsmt Unf SF      2636 non-null   float64
 12  Total Bsmt SF    2636 non-null   float64
 13  1st Flr SF       2637 non-null   int64
 14  2nd Flr SF       2637 non-null   int64
 15  Low Qual Fin SF  2637 non-null   int64
 16  Gr Liv Area      2637 non-null   int64
 17  Bsmt Full Bath   2635 non-null   float64
 18  Bsmt Half Bath   2635 non-null   float64
 19  Full Bath        2637 non-null   int64
 20  Half Bath        2637 non-null   int64
 21  Bedroom AbvGr    2637 non-null   int64
 22  Kitchen AbvGr    2637 non-null   int64
 23  TotRms AbvGrd    2637 non-null   int64
 24  Fireplaces       2637 non-null   int64
 25  Garage Yr Blt    2490 non-null   float64
 26  Garage Cars      2636 non-null   float64
 27  Garage Area      2636 non-null   float64
 28  Wood Deck SF     2637 non-null   int64
 29  Open Porch SF    2637 non-null   int64
 30  Enclosed Porch   2637 non-null   int64
 31  3Ssn Porch       2637 non-null   int64
 32  Screen Porch     2637 non-null   int64
 33  Pool Area        2637 non-null   int64
 34  Misc Val         2637 non-null   int64
 35  Mo Sold          2637 non-null   int64
 36  Yr Sold          2637 non-null   int64
 37  SalePrice        2637 non-null   int64
dtypes: float64(11), int64(27)
memory usage: 783.0 KB

- describe

In [ ]:
# describe
df.describe()

,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2.637000e+03,2637.000000,2188.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2614.000000,2636.000000,...,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000
mean,7.141301e+08,57.349261,69.166819,10044.694729,6.097459,5.569966,1971.288586,1984.202882,101.887911,438.441199,...,94.305271,46.984452,22.813424,2.368601,15.775123,2.130072,42.014031,6.243838,2007.795601,179986.230186
std,1.887527e+08,42.499091,23.356779,6742.549521,1.411522,1.118262,30.306986,20.913077,179.578232,449.602326,...,126.927272,66.564333,61.177638,23.160600,55.783751,35.140140,393.158781,2.722093,1.306403,78309.251522
min,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,5.284770e+08,20.000000,58.000000,7436.000000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,5.354530e+08,50.000000,68.000000,9450.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,368.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,9.071870e+08,70.000000,80.000000,11526.000000,7.000000,6.000000,2001.000000,2004.000000,164.000000,732.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213000.000000
max,1.007100e+09,190.000000,313.000000,164660.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1424.000000,742.000000,584.000000,407.000000,576.000000,800.000000,12500.000000,12.000000,2010.000000,745000.000000

- nunique

In [ ]:
# nunique
df.nunique().sort_values( ascending = False )

PID                2637
Lot Area           1799
Gr Liv Area        1216
Bsmt Unf SF        1080
1st Flr SF         1022
Total Bsmt SF      1001
SalePrice           983
BsmtFin SF 1        935
2nd Flr SF          589
Garage Area         576
Mas Vnr Area        425
Wood Deck SF        367
BsmtFin SF 2        253
Open Porch SF       238
Enclosed Porch      175
Lot Frontage        126
Year Built          118
Screen Porch        115
Garage Yr Blt       102
Year Remod/Add       61
Misc Val             35
Low Qual Fin SF      31
3Ssn Porch           26
MS SubClass          16
Mo Sold              12
Pool Area            12
TotRms AbvGrd        12
Overall Qual         10
Overall Cond          9
Bedroom AbvGr         7
Garage Cars           6
Fireplaces            5
Yr Sold               5
Full Bath             5
Bsmt Full Bath        4
Kitchen AbvGr         4
Half Bath             3
Bsmt Half Bath        3
dtype: int64

In [ ]:
# normalize to look for ID column(s)
df.nunique().sort_values( ascending = False ) / df.shape[0] * 100

PID                100.000000
Lot Area            68.221464
Gr Liv Area         46.113007
Bsmt Unf SF         40.955631
1st Flr SF          38.756162
Total Bsmt SF       37.959803
SalePrice           37.277209
BsmtFin SF 1        35.456959
2nd Flr SF          22.335988
Garage Area         21.843003
Mas Vnr Area        16.116799
Wood Deck SF        13.917330
BsmtFin SF 2         9.594236
Open Porch SF        9.025408
Enclosed Porch       6.636329
Lot Frontage         4.778157
Year Built           4.474782
Screen Porch         4.361016
Garage Yr Blt        3.868032
Year Remod/Add       2.313235
Misc Val             1.327266
Low Qual Fin SF      1.175578
3Ssn Porch           0.985969
MS SubClass          0.606750
Mo Sold              0.455063
Pool Area            0.455063
TotRms AbvGrd        0.455063
Overall Qual         0.379219
Overall Cond         0.341297
Bedroom AbvGr        0.265453
Garage Cars          0.227531
Fireplaces           0.189609
Yr Sold              0.189609
Full Bath            0.189609
Bsmt Full Bath       0.151688
Kitchen AbvGr        0.151688
Half Bath            0.113766
Bsmt Half Bath       0.113766
dtype: float64

- unique

In [ ]:
# unique
df[target_col].unique()

array([115400,  90000, 141000, 254000, 155000, 125000, 194500, 185000,
       235000, 152000, 201000, 207000, 192000, 174000, 190000, 176000,
       384500, 395039, 167000, 165000, 195000, 104500, 161000, 245700,
       226001, 153500, 139000,  35000, 181000, 212000, 156000, 139500,
       225000,  12789, 157500, 110000, 130000, 263000, 205000, 117000,
       200624, 120000, 137900, 245500, 107000, 327000,  93000, 145250,
       168000, 169900, 122000, 161750, 188000, 149500, 421250, 305000,
        50138, 136000, 150750, 307000, 241000,  86900, 202500,  93500,
       121000, 107500, 336000, 213000, 129000, 170000, 337500, 535000,
       173500, 162000,  37900, 158500,  94000, 350000, 140000, 409900,
       115000, 177000,  94750, 121600, 128500, 301000, 230000, 151000,
       137500,  85500, 129400, 191500, 250000, 135000, 119000, 150000,
       178000, 163900, 199000, 203000, 178900, 180000, 182000, 177900,
       122500, 134900, 132000, 147983,  68500, 158000, 260261,  64500,
       140500, 222000, 301500, 138500, 113000, 135750, 213500, 197900,
       134432, 270000, 237000, 196000, 167840, 151400, 138000, 118000,
       159434, 160000,  99500, 311872, 240000, 144000, 145400, 584500,
       230500, 315000, 216837, 183000, 143000, 229456,  85000, 108500,
        89500, 109500, 127000, 235128,  76500, 254900, 188900, 149900,
       154000, 251000,  88000, 143500, 157000, 269790, 105000, 120500,
       104900, 171000,  58500, 234000, 272500, 215000, 129250, 106900,
       214000, 175000, 262500, 300000, 112000, 193879, 137000, 139950,
       142000, 187500, 188500, 209500, 126000, 119500, 120750, 111000,
       135500, 126500, 201800, 128250, 114500, 290000, 167800, 124000,
       102000, 197000, 236000, 249000, 152400, 194000, 379000, 184900,
       103000, 139400, 172500,  75190, 445000, 125500, 128000, 159900,
       333168, 172000, 280000, 184000,  97000, 154400, 259500, 154500,
       116000, 167900, 470000,  62383,  99900, 190550, 108000, 356000,
       186000, 239000, 119164,  97500, 212700, 129900, 287500, 172400,
       260000, 131000, 102776, 216500, 186700, 169000, 106000, 233170,
       212500, 293000, 325300, 394432, 152500, 610000, 294000, 150909,
       209700, 403000, 207500, 215700, 303477, 412083, 356383,  57625,
       147500, 145000, 321000, 146000, 235500, 293200, 438780, 148000,
       185500, 141500, 156500, 192100,  87000,  13100, 200000, 104000,
       132500, 166000, 255500, 159895, 198500, 183900, 263435,  68400,
        98000, 112500, 386250, 210000, 111900, 140750, 128950, 243500,
       238500, 200141, 124500, 171900, 277000,  82000, 239900,  83000,
       210900, 136900, 229800, 217500, 258000, 228500, 218000, 221300,
       164500, 111250, 181755, 103500, 194700, 163000, 342000, 173000,
       133000, 187000, 203135, 257500, 335000, 100500, 191000,  87500,
       147000, 214900, 213250, 160500, 134000, 213490, 168500, 220000,
        93900, 501837, 136500, 161900, 301600, 179665, 151500, 217300,
        82500, 255000, 372000, 114900,  80000, 278000, 189000, 159000,
       222500, 147900, 462000, 285000, 404000, 133500, 264966, 223000,
       117250, 119916, 319900,  95000,  96000, 274000, 492000, 219000,
       153000, 119900, 309000, 153337, 164000, 107400, 217000, 255900,
       211000, 165250, 130500, 227000, 383970, 118500, 148800, 129500,
       105900, 227875, 123000, 113500, 177625, 320000,  79400, 149300,
       119200,  60000, 149000, 310013, 180500,  68104, 117500,  78500,
       193500, 148400, 186800, 131500,  34900, 341000, 126175, 189950,
        79900, 372402, 275000, 181900, 175500, 315500, 219500, 153575,
       325624, 186500, 197600, 137250, 269500, 218836, 206580, 138800,
       261500, 377426, 241600, 224500, 124400, 475000, 235876, 265000,
       145500, 143750, 185101,  67000, 183600,  95541, 116500, 136870,
       163990, 111500, 109900, 123500, 256300, 237500, 179400, 253293,
       485000, 134800, 370967, 138400,  84900, 125200, 228950, 118858,
       129200, 139900, 226700, 196500, 114504, 283463,  91900, 193000,
       161500,  81000,  93850, 163500, 259000, 100000, 172900,  79000,
       176500, 228000,  80900, 375000, 159500, 122600, 198600, 164900,
       337000, 130250, 166500, 248500, 232000, 125900, 246500, 111750,
       162500, 133700, 362500, 253000, 265979, 299800, 178400, 322400,
       336860, 355000, 226000,  75000, 256000, 340000,  92000, 325000,
       295000, 281500, 133900, 167500, 279700, 138887, 145100, 256900,
       179900, 310090, 144750, 204500, 306000, 437154, 324000, 345000,
       213750, 295493, 192140, 189500, 185485,  96900, 302000,  67500,
       181500, 252678,  55000,  72000, 370000, 204000,  81400, 216000,
       145900, 120875, 360000, 287000, 241500, 200500, 221500, 284700,
       312500, 179540, 392000, 378500, 318000, 174850, 146800, 322500,
       254750, 128600, 116900,  91000, 149350, 177500, 204750, 361919,
       175900, 123600,  61500, 129850,  63000, 143900, 169990, 287602,
       158450, 198000, 310000, 221370, 199900, 276000, 281213, 189900,
       323262, 231000, 156932, 171500, 330000, 239500, 171925, 150500,
       179000,  86000, 187750, 169500, 292500, 198444, 162900, 140200,
        99000, 147400,  84000, 119750, 136300, 191750, 127500, 382500,
       110500,  61000, 134500,  80500, 410000, 197500, 291000, 167240,
       248900, 142600, 290941, 199500, 165400,  81300, 128200, 271000,
       398800, 124900, 221000,  98300, 165500, 326000, 257000, 224900,
       319500, 179500, 249700, 229000, 165150, 128900, 146500, 188700,
       117600, 131400, 359900, 245000, 297000, 103600, 136905, 252000,
       500000,  73000, 318061, 208000, 282500, 500067, 209000, 556581,
       142500, 268000, 169985, 239799, 377500, 244600, 183500, 266500,
       142953,  94900, 206300, 390000, 144500, 311500, 146900, 200825,
       450000, 144152,  99600, 114000, 204900, 298236, 318750, 260400,
       316600, 267000, 119600, 195500, 465000, 165600, 108480, 176400,
       374000, 359100,  64000, 185900, 394617, 101800, 334000, 212999,
       185850, 274725, 144900, 184500, 263550, 316500, 286000, 149700,
       147110, 105500, 328000, 187100, 281000, 153600, 155900, 282922,
       294464, 231500, 102900, 349265,  40000, 153900, 176432,  81500,
       168165, 208900, 122900, 244000, 279500, 242500, 124100, 192350,
       103200, 112900,  79500, 376162, 257076,  39300, 402000, 354000,
        96500,  89000, 279900, 244400, 142100, 160250, 277500, 415000,
       395000, 148500, 177439, 154300, 385000, 271900, 208500, 223500,
       298751,  72500,  84500,  35311, 218689,  45000, 109008, 179200,
       150900, 121500,  50000, 279000, 193800,  75500, 275500, 545224,
       123900, 239686, 457347, 248000, 418000,  76000, 212300, 177594,
       246578, 135960,  90350, 236500, 113722, 238000, 176485, 242000,
       156450,  99800, 378000, 219210, 137450, 168675, 555000, 206000,
       206900, 231713, 194201, 395192, 260116, 113700, 266000, 243000,
       280750, 170440, 132250, 131250,  66500, 200100, 154900, 226750,
       166800, 103400,  62500,  91500,  94500, 426000, 155891, 308030,
       129800,  80400, 214500, 248328, 179600,  52500, 372500, 246990,
       615000, 264132, 164990, 383000, 345474, 392500,  51689,  79275,
       263400, 209200,  93369, 230348, 135900,  91300, 466500, 108538,
       336820, 338500, 192500, 131900, 184750, 381000, 441929,  85400,
       144800, 319000, 339750, 180400, 224243, 201490,  59000, 178740,
       268500, 284000, 297900, 262000, 155835, 107900, 479069, 187687,
        52000, 154204, 245350, 367294, 179781, 190500,  87550, 468000,
        78000, 329900, 185088, 372397, 183200, 267300, 232500, 305900,
       417500, 202900, 370878,  83500, 213133, 328900, 412500, 233000,
       317500, 142250, 118900, 202665, 611657, 227680,  68000, 405749,
       106250, 338931, 387000, 315750, 446261, 203160, 267916, 332000,
       455000, 178750,  71000,  65000, 232698, 247000,  70000, 224000,
       106500, 143250, 265900, 313000, 131750, 240050, 401179, 184100,
       240900, 226500, 157900, 289000, 219990, 109000, 156820, 143450,
       287090, 274300, 286500, 139600, 118964, 405000, 172785, 233230,
       146300, 316000,  98600, 402861, 538000, 250580, 233500,  88750,
       195800, 274970, 173900, 173733, 233555,  97900, 198900, 208300,
       284500, 142125, 167300, 142900, 148325, 272000, 215200, 373000,
       262280, 115500, 332200, 419005, 210400,  82375, 160200, 247900,
       745000, 234250,  98500, 174500, 282000,  55993, 314813, 625000,
       182900,  44000, 212109, 232600, 118400, 415298, 174190, 158900,
        94550, 143195, 171750, 264500, 221800, 205950, 344133, 246000,
       451950, 195400, 159950, 369900,  89900, 174900, 211500])

- isnull

In [ ]:
# isnull
df.isnull().sum().sort_values( ascending = False )

Lot Frontage       449
Garage Yr Blt      147
Mas Vnr Area        23
Bsmt Half Bath       2
Bsmt Full Bath       2
Total Bsmt SF        1
Garage Cars          1
Garage Area          1
Bsmt Unf SF          1
BsmtFin SF 1         1
BsmtFin SF 2         1
PID                  0
Lot Area             0
MS SubClass          0
Overall Cond         0
Overall Qual         0
1st Flr SF           0
2nd Flr SF           0
Gr Liv Area          0
Year Built           0
Low Qual Fin SF      0
Year Remod/Add       0
Bedroom AbvGr        0
Half Bath            0
Full Bath            0
Kitchen AbvGr        0
Fireplaces           0
TotRms AbvGrd        0
Wood Deck SF         0
Open Porch SF        0
Enclosed Porch       0
3Ssn Porch           0
Screen Porch         0
Pool Area            0
Misc Val             0
Mo Sold              0
Yr Sold              0
SalePrice            0
dtype: int64

In [ ]:
# percent null by column
(df.isnull().sum() / df.shape[0]).sort_values( ascending = False ) * 100

Lot Frontage       17.026925
Garage Yr Blt       5.574516
Mas Vnr Area        0.872203
Bsmt Half Bath      0.075844
Bsmt Full Bath      0.075844
Total Bsmt SF       0.037922
Garage Cars         0.037922
Garage Area         0.037922
Bsmt Unf SF         0.037922
BsmtFin SF 1        0.037922
BsmtFin SF 2        0.037922
PID                 0.000000
Lot Area            0.000000
MS SubClass         0.000000
Overall Cond        0.000000
Overall Qual        0.000000
1st Flr SF          0.000000
2nd Flr SF          0.000000
Gr Liv Area         0.000000
Year Built          0.000000
Low Qual Fin SF     0.000000
Year Remod/Add      0.000000
Bedroom AbvGr       0.000000
Half Bath           0.000000
Full Bath           0.000000
Kitchen AbvGr       0.000000
Fireplaces          0.000000
TotRms AbvGrd       0.000000
Wood Deck SF        0.000000
Open Porch SF       0.000000
Enclosed Porch      0.000000
3Ssn Porch          0.000000
Screen Porch        0.000000
Pool Area           0.000000
Misc Val            0.000000
Mo Sold             0.000000
Yr Sold             0.000000
SalePrice           0.000000
dtype: float64

In [ ]:
# look at unique values in the col-by-col null counts to classify cols
((df.isnull().sum() / df.shape[0]).sort_values( ascending = False ) * 100).unique()

array([17.02692454,  5.5745165 ,  0.87220326,  0.07584376,  0.03792188,
        0.        ])

In [ ]:
# check to see if anything is not zero -- should return 0 if no nulls
df.isnull().sum().sum()

np.int64(629)

In [ ]:
# how many rows with at least one null
num_rows_with_nulls = df.isna().any(axis=1).sum()
int(num_rows_with_nulls)

604

Many different null counts exist throughout the data set, indicating that this will not be a straightforward nulls cleanup.

- dtypes

In [ ]:
# dtypes
df.dtypes

PID                  int64
MS SubClass          int64
Lot Frontage       float64
Lot Area             int64
Overall Qual         int64
Overall Cond         int64
Year Built           int64
Year Remod/Add       int64
Mas Vnr Area       float64
BsmtFin SF 1       float64
BsmtFin SF 2       float64
Bsmt Unf SF        float64
Total Bsmt SF      float64
1st Flr SF           int64
2nd Flr SF           int64
Low Qual Fin SF      int64
Gr Liv Area          int64
Bsmt Full Bath     float64
Bsmt Half Bath     float64
Full Bath            int64
Half Bath            int64
Bedroom AbvGr        int64
Kitchen AbvGr        int64
TotRms AbvGrd        int64
Fireplaces           int64
Garage Yr Blt      float64
Garage Cars        float64
Garage Area        float64
Wood Deck SF         int64
Open Porch SF        int64
Enclosed Porch       int64
3Ssn Porch           int64
Screen Porch         int64
Pool Area            int64
Misc Val             int64
Mo Sold              int64
Yr Sold              int64
SalePrice            int64
dtype: object

Examine null columns, columns with some nulls, and columns with no nulls:

In [ ]:
# display columns with all null values
df.isnull().sum()[df.isnull().sum() == df.shape[0]]

Series([], dtype: int64)

In [ ]:
# count these
int(df.isnull().sum()[df.isnull().sum() == df.shape[0]].count())

0

In [ ]:
# show columns with some null values
df.isnull().sum()[(df.isnull().sum() != df.shape[0]) & (df.isnull().sum() != 0)].sort_values( ascending = False )

Lot Frontage      449
Garage Yr Blt     147
Mas Vnr Area       23
Bsmt Half Bath      2
Bsmt Full Bath      2
BsmtFin SF 1        1
BsmtFin SF 2        1
Total Bsmt SF       1
Bsmt Unf SF         1
Garage Cars         1
Garage Area         1
dtype: int64

In [ ]:
# count these
int(df.isnull().sum()[(df.isnull().sum() != df.shape[0]) & (df.isnull().sum() != 0)].count())

11

In [ ]:
# columns with no nulls
df.isnull().sum()[df.isnull().sum() == 0]

PID                0
MS SubClass        0
Lot Area           0
Overall Qual       0
Overall Cond       0
Year Built         0
Year Remod/Add     0
1st Flr SF         0
2nd Flr SF         0
Low Qual Fin SF    0
Gr Liv Area        0
Full Bath          0
Half Bath          0
Bedroom AbvGr      0
Kitchen AbvGr      0
TotRms AbvGrd      0
Fireplaces         0
Wood Deck SF       0
Open Porch SF      0
Enclosed Porch     0
3Ssn Porch         0
Screen Porch       0
Pool Area          0
Misc Val           0
Mo Sold            0
Yr Sold            0
SalePrice          0
dtype: int64

In [ ]:
# count these
int(df.isnull().sum()[df.isnull().sum() == 0].count())

27

#### Target: Value Counts

In [ ]:
# value counts on target
df[target_col].value_counts( dropna = False )

SalePrice
140000    31
135000    30
130000    28
155000    24
160000    22
          ..
160200     1
174190     1
415298     1
118400     1
232600     1
Name: count, Length: 983, dtype: int64

In [ ]:
# value counts normalized
df[target_col].value_counts( dropna = False, normalize = True ) * 100

SalePrice
140000    1.175578
135000    1.137656
130000    1.061813
155000    0.910125
160000    0.834281
            ...
160200    0.037922
174190    0.037922
415298    0.037922
118400    0.037922
232600    0.037922
Name: proportion, Length: 983, dtype: float64

In [ ]:
# target col size/shape
df[[target_col]].shape[0]

2637

In [ ]:
# sum of nulls in target
int(df[[target_col]].isnull().sum().iloc[0])

0

In [ ]:
# sum of non-nulls in target
df[[target_col]].shape[0] - int(df[[target_col]].isnull().sum().iloc[0])

2637

There are no nulls in the target column, which means no rows will need to be dropped on its account.

#### Summary:

The floats+ints-feature dataset contains 2637 rows and 38 columns, making for a total of 100206 entries of data. Many of these fields are null.

Details:

  - target column: 'SalePrice'
  - feature columns: [
       'Lot Frontage', 'Garage Yr Blt', 'Mas Vnr Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'BsmtFin SF 2', 'BsmtFin SF 1', 'Total Bsmt SF',
       'Bsmt Unf SF', 'Garage Area', 'Garage Cars',
       'MS SubClass', 'Lot Area', 'Overall Qual', 'Overall Cond', 'Year Built', 'Year Remod/Add', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Full Bath', 'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd', 'Fireplaces', 'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold'
       ]
  - identifier columns: 'PID'
  - null columns: 0
  - null rows (target): 0
  - null rows (any): 2637 (100%)

#### If there are data cleaning issues, develop recommendations for how to deal with them.  Specifically, handle these common issues:

    - identifer columns
    - target column with null counts
    - feature columns with high null counts
    - feature columns with low null counts
    - feature columns with medium null counts

First, make a backup:

In [ ]:
# make backup
df_bak = df.copy()

In [ ]:
# restore from backup
df = df_bak.copy()

In [ ]:
# df again to double-check
df

,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,905101070,20,62.0,14299,4,3,1964,1964,0.0,513.0,...,0,0,0,0,0,0,0,7,2007,115400
1,905101330,90,72.0,10791,4,5,1967,1967,0.0,0.0,...,0,0,0,0,0,0,500,10,2006,90000
2,903454090,50,50.0,9000,6,6,1937,1950,0.0,0.0,...,0,162,0,0,126,0,0,12,2007,141000
3,533244030,60,68.0,7379,8,5,2000,2000,0.0,484.0,...,280,184,0,0,0,0,0,4,2010,254000
4,909252020,70,60.0,7200,7,9,1936,2007,0.0,350.0,...,256,0,0,0,0,0,0,4,2009,155000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2632,903231070,50,52.0,6240,6,6,1934,1950,0.0,0.0,...,112,0,0,0,0,0,400,9,2006,114500
2633,906201021,80,74.0,10778,7,6,1990,1991,0.0,460.0,...,114,36,0,0,0,0,0,7,2009,162000
2634,533253070,120,61.0,3782,8,5,1981,1981,0.0,960.0,...,133,78,0,0,0,0,0,9,2009,211500
2635,527376100,20,78.0,10140,6,5,1974,1974,174.0,0.0,...,0,0,0,0,0,0,0,8,2009,165000
2636,528292060,60,41.0,12460,7,5,1999,2000,0.0,870.0,...,144,44,0,0,0,0,0,5,2008,225000

1. Remove identifier columns

In [ ]:
# remove identifier columns from DataFrame
df = df.drop( columns = [ 'PID' ] )

In [ ]:
# backup 1
df_bak1 = df.copy()

In [ ]:
# restore from backup 1
df = df_bak1.copy()

In [ ]:
df

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,20,62.0,14299,4,3,1964,1964,0.0,513.0,144.0,...,0,0,0,0,0,0,0,7,2007,115400
1,90,72.0,10791,4,5,1967,1967,0.0,0.0,0.0,...,0,0,0,0,0,0,500,10,2006,90000
2,50,50.0,9000,6,6,1937,1950,0.0,0.0,0.0,...,0,162,0,0,126,0,0,12,2007,141000
3,60,68.0,7379,8,5,2000,2000,0.0,484.0,0.0,...,280,184,0,0,0,0,0,4,2010,254000
4,70,60.0,7200,7,9,1936,2007,0.0,350.0,210.0,...,256,0,0,0,0,0,0,4,2009,155000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2632,50,52.0,6240,6,6,1934,1950,0.0,0.0,0.0,...,112,0,0,0,0,0,400,9,2006,114500
2633,80,74.0,10778,7,6,1990,1991,0.0,460.0,286.0,...,114,36,0,0,0,0,0,7,2009,162000
2634,120,61.0,3782,8,5,1981,1981,0.0,960.0,0.0,...,133,78,0,0,0,0,0,9,2009,211500
2635,20,78.0,10140,6,5,1974,1974,174.0,0.0,0.0,...,0,0,0,0,0,0,0,8,2009,165000
2636,60,41.0,12460,7,5,1999,2000,0.0,870.0,0.0,...,144,44,0,0,0,0,0,5,2008,225000

2. Drop null target rows

- No null target rows

3. Drop feature columns with many or all nulls

In [ ]:
df.isnull().sum().sort_values( ascending = False )

Lot Frontage       449
Garage Yr Blt      147
Mas Vnr Area        23
Bsmt Full Bath       2
Bsmt Half Bath       2
Garage Cars          1
Garage Area          1
Bsmt Unf SF          1
BsmtFin SF 1         1
Total Bsmt SF        1
BsmtFin SF 2         1
Lot Area             0
MS SubClass          0
Overall Cond         0
Overall Qual         0
1st Flr SF           0
2nd Flr SF           0
Gr Liv Area          0
Year Built           0
Low Qual Fin SF      0
Year Remod/Add       0
Bedroom AbvGr        0
Half Bath            0
Full Bath            0
Kitchen AbvGr        0
Fireplaces           0
TotRms AbvGrd        0
Wood Deck SF         0
Open Porch SF        0
Enclosed Porch       0
3Ssn Porch           0
Screen Porch         0
Pool Area            0
Misc Val             0
Mo Sold              0
Yr Sold              0
SalePrice            0
dtype: int64

In [ ]:
# df = df.loc[:, df.isnull().mean() <= 0.5]
df = df.drop( columns = [index for index in list(df.isnull().sum().index) if (df.isnull().sum().loc[index] / df.shape[0] > 0.4)])

In [ ]:
df

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,20,62.0,14299,4,3,1964,1964,0.0,513.0,144.0,...,0,0,0,0,0,0,0,7,2007,115400
1,90,72.0,10791,4,5,1967,1967,0.0,0.0,0.0,...,0,0,0,0,0,0,500,10,2006,90000
2,50,50.0,9000,6,6,1937,1950,0.0,0.0,0.0,...,0,162,0,0,126,0,0,12,2007,141000
3,60,68.0,7379,8,5,2000,2000,0.0,484.0,0.0,...,280,184,0,0,0,0,0,4,2010,254000
4,70,60.0,7200,7,9,1936,2007,0.0,350.0,210.0,...,256,0,0,0,0,0,0,4,2009,155000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2632,50,52.0,6240,6,6,1934,1950,0.0,0.0,0.0,...,112,0,0,0,0,0,400,9,2006,114500
2633,80,74.0,10778,7,6,1990,1991,0.0,460.0,286.0,...,114,36,0,0,0,0,0,7,2009,162000
2634,120,61.0,3782,8,5,1981,1981,0.0,960.0,0.0,...,133,78,0,0,0,0,0,9,2009,211500
2635,20,78.0,10140,6,5,1974,1974,174.0,0.0,0.0,...,0,0,0,0,0,0,0,8,2009,165000
2636,60,41.0,12460,7,5,1999,2000,0.0,870.0,0.0,...,144,44,0,0,0,0,0,5,2008,225000

In [ ]:
list(df.isnull().sum().index)

['MS SubClass',
 'Lot Frontage',
 'Lot Area',
 'Overall Qual',
 'Overall Cond',
 'Year Built',
 'Year Remod/Add',
 'Mas Vnr Area',
 'BsmtFin SF 1',
 'BsmtFin SF 2',
 'Bsmt Unf SF',
 'Total Bsmt SF',
 '1st Flr SF',
 '2nd Flr SF',
 'Low Qual Fin SF',
 'Gr Liv Area',
 'Bsmt Full Bath',
 'Bsmt Half Bath',
 'Full Bath',
 'Half Bath',
 'Bedroom AbvGr',
 'Kitchen AbvGr',
 'TotRms AbvGrd',
 'Fireplaces',
 'Garage Yr Blt',
 'Garage Cars',
 'Garage Area',
 'Wood Deck SF',
 'Open Porch SF',
 'Enclosed Porch',
 '3Ssn Porch',
 'Screen Porch',
 'Pool Area',
 'Misc Val',
 'Mo Sold',
 'Yr Sold',
 'SalePrice']

In [ ]:
df.shape

(2637, 37)

4. Drop remaining records with null counts (if few)

In [ ]:
# backup 2
df_bak2 = df.copy()

In [ ]:
# restore from backup 2
df = df_bak2.copy()

In [ ]:
df

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,20,62.0,14299,4,3,1964,1964,0.0,513.0,144.0,...,0,0,0,0,0,0,0,7,2007,115400
1,90,72.0,10791,4,5,1967,1967,0.0,0.0,0.0,...,0,0,0,0,0,0,500,10,2006,90000
2,50,50.0,9000,6,6,1937,1950,0.0,0.0,0.0,...,0,162,0,0,126,0,0,12,2007,141000
3,60,68.0,7379,8,5,2000,2000,0.0,484.0,0.0,...,280,184,0,0,0,0,0,4,2010,254000
4,70,60.0,7200,7,9,1936,2007,0.0,350.0,210.0,...,256,0,0,0,0,0,0,4,2009,155000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2632,50,52.0,6240,6,6,1934,1950,0.0,0.0,0.0,...,112,0,0,0,0,0,400,9,2006,114500
2633,80,74.0,10778,7,6,1990,1991,0.0,460.0,286.0,...,114,36,0,0,0,0,0,7,2009,162000
2634,120,61.0,3782,8,5,1981,1981,0.0,960.0,0.0,...,133,78,0,0,0,0,0,9,2009,211500
2635,20,78.0,10140,6,5,1974,1974,174.0,0.0,0.0,...,0,0,0,0,0,0,0,8,2009,165000
2636,60,41.0,12460,7,5,1999,2000,0.0,870.0,0.0,...,144,44,0,0,0,0,0,5,2008,225000

In [ ]:
df.isnull().sum().sort_values( ascending = False )

Lot Frontage       449
Garage Yr Blt      147
Mas Vnr Area        23
Bsmt Full Bath       2
Bsmt Half Bath       2
Garage Cars          1
Garage Area          1
Bsmt Unf SF          1
BsmtFin SF 1         1
Total Bsmt SF        1
BsmtFin SF 2         1
Lot Area             0
MS SubClass          0
Overall Cond         0
Overall Qual         0
1st Flr SF           0
2nd Flr SF           0
Gr Liv Area          0
Year Built           0
Low Qual Fin SF      0
Year Remod/Add       0
Bedroom AbvGr        0
Half Bath            0
Full Bath            0
Kitchen AbvGr        0
Fireplaces           0
TotRms AbvGrd        0
Wood Deck SF         0
Open Porch SF        0
Enclosed Porch       0
3Ssn Porch           0
Screen Porch         0
Pool Area            0
Misc Val             0
Mo Sold              0
Yr Sold              0
SalePrice            0
dtype: int64

In [ ]:
df = df.dropna(subset=[index for index in list(df.isnull().sum().index) if (df.isnull().sum().loc[index] / df.shape[0] < 0.05)])

In [ ]:
df

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,20,62.0,14299,4,3,1964,1964,0.0,513.0,144.0,...,0,0,0,0,0,0,0,7,2007,115400
1,90,72.0,10791,4,5,1967,1967,0.0,0.0,0.0,...,0,0,0,0,0,0,500,10,2006,90000
2,50,50.0,9000,6,6,1937,1950,0.0,0.0,0.0,...,0,162,0,0,126,0,0,12,2007,141000
3,60,68.0,7379,8,5,2000,2000,0.0,484.0,0.0,...,280,184,0,0,0,0,0,4,2010,254000
4,70,60.0,7200,7,9,1936,2007,0.0,350.0,210.0,...,256,0,0,0,0,0,0,4,2009,155000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2632,50,52.0,6240,6,6,1934,1950,0.0,0.0,0.0,...,112,0,0,0,0,0,400,9,2006,114500
2633,80,74.0,10778,7,6,1990,1991,0.0,460.0,286.0,...,114,36,0,0,0,0,0,7,2009,162000
2634,120,61.0,3782,8,5,1981,1981,0.0,960.0,0.0,...,133,78,0,0,0,0,0,9,2009,211500
2635,20,78.0,10140,6,5,1974,1974,174.0,0.0,0.0,...,0,0,0,0,0,0,0,8,2009,165000
2636,60,41.0,12460,7,5,1999,2000,0.0,870.0,0.0,...,144,44,0,0,0,0,0,5,2008,225000

In [ ]:
list(df.isnull().sum().index)

['MS SubClass',
 'Lot Frontage',
 'Lot Area',
 'Overall Qual',
 'Overall Cond',
 'Year Built',
 'Year Remod/Add',
 'Mas Vnr Area',
 'BsmtFin SF 1',
 'BsmtFin SF 2',
 'Bsmt Unf SF',
 'Total Bsmt SF',
 '1st Flr SF',
 '2nd Flr SF',
 'Low Qual Fin SF',
 'Gr Liv Area',
 'Bsmt Full Bath',
 'Bsmt Half Bath',
 'Full Bath',
 'Half Bath',
 'Bedroom AbvGr',
 'Kitchen AbvGr',
 'TotRms AbvGrd',
 'Fireplaces',
 'Garage Yr Blt',
 'Garage Cars',
 'Garage Area',
 'Wood Deck SF',
 'Open Porch SF',
 'Enclosed Porch',
 '3Ssn Porch',
 'Screen Porch',
 'Pool Area',
 'Misc Val',
 'Mo Sold',
 'Yr Sold',
 'SalePrice']

In [ ]:
df.shape

(2611, 37)

5.  impute with the median for remaining fields

In [ ]:
# backup 3
df_bak3 = df.copy()

In [ ]:
# restore from backup 3
df = df_bak3.copy()

In [ ]:
df

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,20,62.0,14299,4,3,1964,1964,0.0,513.0,144.0,...,0,0,0,0,0,0,0,7,2007,115400
1,90,72.0,10791,4,5,1967,1967,0.0,0.0,0.0,...,0,0,0,0,0,0,500,10,2006,90000
2,50,50.0,9000,6,6,1937,1950,0.0,0.0,0.0,...,0,162,0,0,126,0,0,12,2007,141000
3,60,68.0,7379,8,5,2000,2000,0.0,484.0,0.0,...,280,184,0,0,0,0,0,4,2010,254000
4,70,60.0,7200,7,9,1936,2007,0.0,350.0,210.0,...,256,0,0,0,0,0,0,4,2009,155000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2632,50,52.0,6240,6,6,1934,1950,0.0,0.0,0.0,...,112,0,0,0,0,0,400,9,2006,114500
2633,80,74.0,10778,7,6,1990,1991,0.0,460.0,286.0,...,114,36,0,0,0,0,0,7,2009,162000
2634,120,61.0,3782,8,5,1981,1981,0.0,960.0,0.0,...,133,78,0,0,0,0,0,9,2009,211500
2635,20,78.0,10140,6,5,1974,1974,174.0,0.0,0.0,...,0,0,0,0,0,0,0,8,2009,165000
2636,60,41.0,12460,7,5,1999,2000,0.0,870.0,0.0,...,144,44,0,0,0,0,0,5,2008,225000

In [ ]:
# check again how many of each column is null
df.isnull().sum().sort_values( ascending = False )

Lot Frontage       443
Garage Yr Blt      145
MS SubClass          0
Overall Qual         0
Lot Area             0
Overall Cond         0
Year Built           0
Mas Vnr Area         0
Year Remod/Add       0
BsmtFin SF 2         0
Bsmt Unf SF          0
Total Bsmt SF        0
BsmtFin SF 1         0
2nd Flr SF           0
Low Qual Fin SF      0
Gr Liv Area          0
Bsmt Full Bath       0
Bsmt Half Bath       0
Full Bath            0
Half Bath            0
1st Flr SF           0
Bedroom AbvGr        0
Kitchen AbvGr        0
TotRms AbvGrd        0
Fireplaces           0
Garage Cars          0
Garage Area          0
Wood Deck SF         0
Open Porch SF        0
Enclosed Porch       0
3Ssn Porch           0
Screen Porch         0
Pool Area            0
Misc Val             0
Mo Sold              0
Yr Sold              0
SalePrice            0
dtype: int64

In [ ]:
# normalize null counts (per column)
df.isnull().sum().sort_values( ascending = False ) / df.shape[0] * 100

Lot Frontage       16.966679
Garage Yr Blt       5.553428
MS SubClass         0.000000
Overall Qual        0.000000
Lot Area            0.000000
Overall Cond        0.000000
Year Built          0.000000
Mas Vnr Area        0.000000
Year Remod/Add      0.000000
BsmtFin SF 2        0.000000
Bsmt Unf SF         0.000000
Total Bsmt SF       0.000000
BsmtFin SF 1        0.000000
2nd Flr SF          0.000000
Low Qual Fin SF     0.000000
Gr Liv Area         0.000000
Bsmt Full Bath      0.000000
Bsmt Half Bath      0.000000
Full Bath           0.000000
Half Bath           0.000000
1st Flr SF          0.000000
Bedroom AbvGr       0.000000
Kitchen AbvGr       0.000000
TotRms AbvGrd       0.000000
Fireplaces          0.000000
Garage Cars         0.000000
Garage Area         0.000000
Wood Deck SF        0.000000
Open Porch SF       0.000000
Enclosed Porch      0.000000
3Ssn Porch          0.000000
Screen Porch        0.000000
Pool Area           0.000000
Misc Val            0.000000
Mo Sold             0.000000
Yr Sold             0.000000
SalePrice           0.000000
dtype: float64

Impute:

In [ ]:
feature_cols = list(df.drop(columns = target_col).columns)
feature_cols

['MS SubClass',
 'Lot Frontage',
 'Lot Area',
 'Overall Qual',
 'Overall Cond',
 'Year Built',
 'Year Remod/Add',
 'Mas Vnr Area',
 'BsmtFin SF 1',
 'BsmtFin SF 2',
 'Bsmt Unf SF',
 'Total Bsmt SF',
 '1st Flr SF',
 '2nd Flr SF',
 'Low Qual Fin SF',
 'Gr Liv Area',
 'Bsmt Full Bath',
 'Bsmt Half Bath',
 'Full Bath',
 'Half Bath',
 'Bedroom AbvGr',
 'Kitchen AbvGr',
 'TotRms AbvGrd',
 'Fireplaces',
 'Garage Yr Blt',
 'Garage Cars',
 'Garage Area',
 'Wood Deck SF',
 'Open Porch SF',
 'Enclosed Porch',
 '3Ssn Porch',
 'Screen Porch',
 'Pool Area',
 'Misc Val',
 'Mo Sold',
 'Yr Sold']

In [ ]:
# loop through features to bulk impute with respective column medians
for feature_col in feature_cols:

  # Calculate the median
  median = df[feature_col].median()
  print(median)

  # Assign median to nulls
  df.fillna( {feature_col: median}, inplace = True )

  # Verify median is about the same as before
  print(df[feature_col].median())

50.0
50.0
68.0
68.0
9434.0
9434.0
6.0
6.0
5.0
5.0
1973.0
1973.0
1993.0
1993.0
0.0
0.0
368.0
368.0
0.0
0.0
463.0
463.0
988.0
988.0
1082.0
1082.0
0.0
0.0
0.0
0.0
1440.0
1440.0
0.0
0.0
0.0
0.0
2.0
2.0
0.0
0.0
3.0
3.0
1.0
1.0
6.0
6.0
1.0
1.0
1979.0
1979.0
2.0
2.0
478.0
478.0
0.0
0.0
27.0
27.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
6.0
6.0
2008.0
2008.0

In [ ]:
df

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,20,62.0,14299,4,3,1964,1964,0.0,513.0,144.0,...,0,0,0,0,0,0,0,7,2007,115400
1,90,72.0,10791,4,5,1967,1967,0.0,0.0,0.0,...,0,0,0,0,0,0,500,10,2006,90000
2,50,50.0,9000,6,6,1937,1950,0.0,0.0,0.0,...,0,162,0,0,126,0,0,12,2007,141000
3,60,68.0,7379,8,5,2000,2000,0.0,484.0,0.0,...,280,184,0,0,0,0,0,4,2010,254000
4,70,60.0,7200,7,9,1936,2007,0.0,350.0,210.0,...,256,0,0,0,0,0,0,4,2009,155000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2632,50,52.0,6240,6,6,1934,1950,0.0,0.0,0.0,...,112,0,0,0,0,0,400,9,2006,114500
2633,80,74.0,10778,7,6,1990,1991,0.0,460.0,286.0,...,114,36,0,0,0,0,0,7,2009,162000
2634,120,61.0,3782,8,5,1981,1981,0.0,960.0,0.0,...,133,78,0,0,0,0,0,9,2009,211500
2635,20,78.0,10140,6,5,1974,1974,174.0,0.0,0.0,...,0,0,0,0,0,0,0,8,2009,165000
2636,60,41.0,12460,7,5,1999,2000,0.0,870.0,0.0,...,144,44,0,0,0,0,0,5,2008,225000

In [ ]:
# check again how many of each column is null
df.isnull().sum().sort_values( ascending = False )

MS SubClass        0
Lot Frontage       0
Lot Area           0
Overall Qual       0
Overall Cond       0
Year Built         0
Year Remod/Add     0
Mas Vnr Area       0
BsmtFin SF 1       0
BsmtFin SF 2       0
Bsmt Unf SF        0
Total Bsmt SF      0
1st Flr SF         0
2nd Flr SF         0
Low Qual Fin SF    0
Gr Liv Area        0
Bsmt Full Bath     0
Bsmt Half Bath     0
Full Bath          0
Half Bath          0
Bedroom AbvGr      0
Kitchen AbvGr      0
TotRms AbvGrd      0
Fireplaces         0
Garage Yr Blt      0
Garage Cars        0
Garage Area        0
Wood Deck SF       0
Open Porch SF      0
Enclosed Porch     0
3Ssn Porch         0
Screen Porch       0
Pool Area          0
Misc Val           0
Mo Sold            0
Yr Sold            0
SalePrice          0
dtype: int64

In [ ]:
# backup 4
df_bak4 = df.copy()

In [ ]:
# restore from backup 4
df = df_bak4.copy()

In [ ]:
df

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,20,62.0,14299,4,3,1964,1964,0.0,513.0,144.0,...,0,0,0,0,0,0,0,7,2007,115400
1,90,72.0,10791,4,5,1967,1967,0.0,0.0,0.0,...,0,0,0,0,0,0,500,10,2006,90000
2,50,50.0,9000,6,6,1937,1950,0.0,0.0,0.0,...,0,162,0,0,126,0,0,12,2007,141000
3,60,68.0,7379,8,5,2000,2000,0.0,484.0,0.0,...,280,184,0,0,0,0,0,4,2010,254000
4,70,60.0,7200,7,9,1936,2007,0.0,350.0,210.0,...,256,0,0,0,0,0,0,4,2009,155000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2632,50,52.0,6240,6,6,1934,1950,0.0,0.0,0.0,...,112,0,0,0,0,0,400,9,2006,114500
2633,80,74.0,10778,7,6,1990,1991,0.0,460.0,286.0,...,114,36,0,0,0,0,0,7,2009,162000
2634,120,61.0,3782,8,5,1981,1981,0.0,960.0,0.0,...,133,78,0,0,0,0,0,9,2009,211500
2635,20,78.0,10140,6,5,1974,1974,174.0,0.0,0.0,...,0,0,0,0,0,0,0,8,2009,165000
2636,60,41.0,12460,7,5,1999,2000,0.0,870.0,0.0,...,144,44,0,0,0,0,0,5,2008,225000

In [ ]:
# check total null counts sum
f"Number of remaining nulls in df: {int(df.isnull().sum().sum())}"

'Number of remaining nulls in df: 0'

#### If there are data cleaning issues, develop recommendations for how to deal with them.  Specifically, handle these common issues:

    - identifer columns
    - target column with null counts
    - feature columns with high null counts
    - feature columns with low null counts
    - feature columns with medium null counts

In [ ]:
# head again to double-check
df.head()

In [ ]:
# make backup
df_bak = df.copy()

In [ ]:
# restore from backup
df = df_bak.copy()

In [ ]:
df

In [ ]:
# Setup drop thresholds

# Drop a column if null % above 85%
drop_column_threshold = 0.85

# Drop a row if null % below 15%
drop_row_threshold = 0.15

1. Remove identifier columns

- No identifier rows present in set (culled at read level)

2. Drop null target rows

- No null target rows

3. Drop feature columns with many or all nulls

In [ ]:
# Select columns where the missing value ratio is less than drop_column_threshold
high_nulls = df.columns[df.isnull().mean() > drop_column_threshold]
high_nulls

In [ ]:
# Drop those specific columns
df = df.drop(columns=high_nulls)
df

4. Drop remaining records with null counts (if few)

In [ ]:
# backup 2
df_bak2 = df.copy()

In [ ]:
# restore from backup 2
df = df_bak2.copy()

In [ ]:
df

In [ ]:
# Select columns where the missing value ratio is less than drop_column_threshold
low_nulls = df.columns[df.isnull().mean() < drop_row_threshold]
low_nulls

In [ ]:
# Drop those specific columns
df = df.dropna(subset=low_nulls)
df

5.  Impute with the median for remaining fields

In [ ]:
# backup 3
df_bak3 = df.copy()

In [ ]:
# restore from backup 3
df = df_bak3.copy()

In [ ]:
# check again how many of each column is null
df.isnull().sum().sort_values( ascending = False )

Impute:

In [ ]:
# Get list of feature cols
feature_cols = list(df.drop(columns = target_col).columns)

# Loop through feature cols to bulk impute
for feature_col in feature_cols:

  # Assign mode to nulls
  mode = df[feature_col].mode(dropna = True)[0]
  df.fillna( {feature_col: mode}, inplace = True )

In [ ]:
# check again how many of each column is null
df.isnull().sum().sort_values( ascending = False )

In [ ]:
# check total null counts sum
f"Number of remaining nulls in df: {int(df.isnull().sum().sum())}"

## Exploratory Data Analysis

In [ ]:
# Plot SalePrice and all of our predictors (features)

# parameterize plot settings
num_cols = 6
num_features = len(df.columns)
num_rows = num_features // num_cols + 1
plot_width = 20
plot_height = 3 * num_rows
column_names = df.columns
hist_y_label = "Count"

# assemble subplot canvas (subplots array)
fig, axs = plt.subplots(num_rows ,num_cols, figsize=(plot_width, plot_height))

# fill subplots
subplots = axs.flatten()
for n, column_name in enumerate(column_names): # Loop through rows
    subplots[n].hist(df[column_name])
    subplots[n].set_xlabel(column_name)
    subplots[n].set_ylabel(hist_y_label)

# hide empty subplots
for i in range(num_features, len(subplots)):
    fig.delaxes(subplots[i])

# format and show
plt.suptitle("Histogram: Object Features & Target", fontsize=24, weight="bold")
plt.tight_layout()
plt.subplots_adjust(top=0.95)
plt.show()

### What do we notice?

- A few of the features — Exterior 1st, Exterior 2nd, House Style, and perhaps Neighborhood — all appear to trend with SalePrice, with all resembling positively-skewed normal distributions
- Perhaps some outliers in the columns

#### Next, we encode the object features in order to look at correlations:

In [ ]:
# Assign numerical values and store in another column
df_encoded = pd.DataFrame(df[target_col])
for feature in feature_cols:
  df_feature = pd.get_dummies(
      pd.DataFrame(df[feature]),
      columns=[feature],
      prefix=feature,
      prefix_sep="_",
      dtype="int"
      )

  df_encoded = pd.concat([df_encoded, df_feature], axis=1, ignore_index=False)

df_encoded

In [ ]:
# backup 4
df_bak4 = df.copy()

In [ ]:
# restore from backup 4
df = df_bak4.copy()

In [ ]:
df

In [ ]:
# update df
df = df_encoded.copy()

Correlation Matrices

In [ ]:
# Let's take a look at a correlation plot
plt.figure(figsize=(10,10))
correlation_matrix = df.corr().round(2)
sns.heatmap(data=correlation_matrix, annot=False, vmin=0, vmax=1, square=True, xticklabels=False, yticklabels=False) ;

In [ ]:
correlation_matrix = df.corr().round(2)
correlation_matrix[target_col].abs().sort_values(ascending=False)

In [ ]:
correlation_matrix = df.corr().round(2)
correlation_matrix[target_col].abs().sort_values(ascending=False).plot( kind="bar", ylim = [0,1])
plt.xticks([])
plt.title("Correlations: Encoded Features to Target (SalePrice)")
plt.xlabel('Feature (Encoded)')
plt.ylabel("Correlation Score") ;

In [ ]:
corrs = df.corr().round(2).unstack().abs()
corrs.reset_index()

In [ ]:
corrs = corrs[corrs < 1]
corrs.reset_index()

In [ ]:
corrs.sort_values(ascending = False).reset_index()

In [ ]:
corrs.sort_values(ascending = False)[::2].reset_index()

### What do we notice?

- After encoding, it is difficult to assess correlations visually among the different variables using a correlation matrix. To do this, we would likely need to cull redundant features and features poorly correlated with the target. However, given the large number of columns, it will still be difficult to prune the data by inspection.

- Hence, we devise a way to automate this process below.

## Processing

### Feature Selection

In [ ]:
corrs_list_half = []
for level_0, level_1 in corrs.index:
  if (level_1, level_0) not in corrs_list_half:
    corrs_list_half.append((level_0, level_1))

corrs_list_half[:10]

In [ ]:
corrs[corrs_list_half].sort_values(ascending=False)

In [ ]:
corrs_list_half_bak = corrs_list_half.copy()

In [ ]:
corrs_list_half = corrs_list_half_bak.copy()

In [ ]:
throwaways = set()
threshold = 0.8
for index_pair in corrs_list_half:
  if corrs[index_pair] >= threshold:
    l0 = index_pair[0]
    l1 = index_pair[1]
    c0 = corrs[(target_col, l0)]
    c1 = corrs[(target_col, l1)]
    throwaways.add(l0 if c0 < c1 else l1)

throwaways

In [ ]:
feat_to_feat_threshold = 0.8
feat_to_target_threshold = 0.05

In [ ]:
feature_cols_object_drop_noise = [col for col in df.columns if correlation_matrix[target_col].abs().loc[col] < feat_to_target_threshold]
feature_cols_object_drop_redundant = list(throwaways)

In [ ]:
feature_cols_object_drop = feature_cols_object_drop_noise + feature_cols_object_drop_redundant + [target_col]
feature_cols_object_drop

In [ ]:
feature_cols_object = list( df.drop( columns = feature_cols_object_drop ) )
target_col, feature_cols_object, feature_cols_object_drop

In [ ]:
# Split data frame into target and features
target           = df[target_col].copy()
features_object  = df[feature_cols_object].copy()

In [ ]:
# Verify features
features_object

In [ ]:
# Verify target
target

In [ ]:
type(features_object), features_object.shape, features_object.ndim

In [ ]:
type(target), target.shape, target.ndim

In [ ]:
# backup 5
df_bak5 = df.copy()

In [ ]:
# restore from backup 5
df = df_bak5.copy()

In [ ]:
df

In [ ]:
# Execute the selection
df = pd.concat([target, features_object], axis=1)
df

### Fit & Assess Our Model

#### Linear Regression — Sklearn

In [ ]:
# define our features set
features = features_object

Now, we perform a linear regression using sklearn:

In [ ]:
# First we run a single split (single holdout) to see what the data looks like:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.2, random_state=42)

In [ ]:
# Fit a linear model using Sklearn
model = LinearRegression()
model.fit(X_train, y_train)

( model.intercept_, model.coef_ )

In [ ]:
# See how well our model performs on our test data
y_pred = model.predict(X_test)
plt.scatter(y_test, y_pred)
plt.plot([min(y_pred), max(y_pred)],[min(y_pred), max(y_pred)], c='red')
plt.xlabel('Actual Sale Price')
plt.ylabel('Predicted Sale Price') ;

In [ ]:
list(zip(y_test,y_pred))[:10]

We'll use RMSE as our performance metric.

In [ ]:
# Calculate root mean squared error on test data
rmse = metrics.mean_squared_error(y_test, y_pred)**0.5
print(f"RMSE: {rmse}")

Evaluate using cross_val_score (Single CV):

In [ ]:
# Use cross validation (k-fold) to assess model performance (Single CV — Single run of a K-Fold loop)
results_cvs = cross_val_score(model, features, target, scoring='neg_root_mean_squared_error', cv = 10)
rmse_cvs = abs(results_cvs.mean())
print(f"CV RMSE: {rmse_cvs}")

Evaulate using CV loop (Multiple CV):

In [ ]:
# Multiple CV loop
n = 500
rmses = []
for i in range(0, n):

  # First we will break up our data into training and testing sets
  X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.2)

  # Fit a linear model using Sklearn
  my_fit_lr = LinearRegression()
  my_fit_lr.fit(X_train, y_train)

  # See how well our model performs on our test data
  y_pred = my_fit_lr.predict(X_test)

  # Capture performance metric (accuracy) in array
  rmses.append(metrics.mean_squared_error(y_test, y_pred)**0.5)

results = np.array(rmses)
results[:10]

In [ ]:
# Calculate mean of results
results.mean()

## Data Visualization/Communication of Results

### Residual Analysis

In [ ]:
# QQ Plot - Residuals are normally distributed
res = y_test - y_pred
sm.qqplot(res, fit=True, line="45") ;

In [ ]:
# Residuals vs Fitted (Predicted) Values - Constant variance
plt.figure(figsize = (10,6))
plt.scatter(y_pred, res)
plt.xlabel("Fitted")
plt.ylabel("Residuals")
plt.hlines(0, min(y_pred), max(y_pred), colors = 'red', linestyles = 'dashed') ;

In [ ]:
# Residuals vs Time - indepedence
plt.figure(figsize = (10,6))
plt.scatter(range(len(res)), res)
plt.plot(range(len(res)), res, 'b')
plt.xlabel("Time")
plt.ylabel("Residuals")
plt.hlines(0, min(range(len(res))), max(range(len(res))), colors = 'red', linestyles = 'dashed') ;

This result tells us that using the categorical (object) features produces the best result obtained so far. The residual analysis still shows some residuals data not conforming to a normal distribution, but most of the data seems to align with our predictions for the object qq plot. More work could be done to improve this result, such as combining the data from all three types, or trying out different models.